---
apiVersion: v1
kind: Service
metadata:
  namespace: elk
  name: elasticsearch-client-http
  labels:
    app: elasticsearch
    role: client
spec:
  type: NodePort
  ports:
  - port: 9200
    name: client
    targetPort: 9200
  selector:
    app: elasticsearch
    role: client
---
apiVersion: v1
kind: Service
metadata:
  namespace: elk
  name: elasticsearch-client
  labels:
    app: elasticsearch
    role: client
spec:
  ports:
  - port: 9300
    name: transport
  selector:
    app: elasticsearch
    role: client
---
