---
apiVersion: v1
kind: Service
metadata:
  namespace: ELK
  name: elasticsearch-client
  labels:
    app: elasticsearch
    role: client
spec:
  ports:
  - port: 9300
    name: transport
  selector:
    app: elasticsearch
    role: client
---
