apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: elk
data:
  # logstash conf
  logstash.yml: |
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
    config.reload.automatic: true

# logstash pipeline
  logstash.conf: |
    input {
      kafka {
        bootstrap_servers => ""
        topics => ["smartstore.goodnara.review","smartstore.drstyle.review","smartstore.thecheaper.review","smartstore.180store.review","smartstore.cloony.review","smartstore.theshopsw.review"]
        consumer_threads => 3
        isolation_level => "read_committed"
        value_deserializer_class => "org.apache.kafka.common.serialization.StringDeserializer"
        auto_offset_reset => "earliest"
      }
    }

    filter {
        mutate {
          gsub => ["message", "[\"/{}]", ""]
        }

         kv {
           field_split => ","
           value_split => ":"
         }
         mutate {
           remove_field => [ "port","@version","host","message" ]
           rename => {" comment" => "comment"}
           rename => {" date" => "date"}
           rename => { " star" => "star" }
         }


        mutate {
          convert => {
            "star" => "integer"
          }
         }
    }

    output {
      stdout { codec => rubydebug }

# ----------------- 스마트 스토어 모자 Topic -----------------
 
	    if [topic] =~ "smartstore.goodnara.review" {
		    elasticsearch {
			    hosts => "http://elasticsearch-client-http.elk.svc.cluster.local:9200"
			    index => "smartstore.goodnara.review-%{+YYYY.MM.dd}"
			    codec => "json"
			    timeout => 120
		    }
	    } # if end

	    else if [topic] =~ "smartstore.drstyle.review" {
		    elasticsearch {
			    hosts => "http://elasticsearch-client-http.elk.svc.cluster.local:9200"
			    index => "smartstore.drstyle.review-%{+YYYY.MM.dd}"
			    codec => "json"
			    timeout => 120
		    }
	    } # if end

	    else if [topic] =~ "smartstore.thecheaper.review" {
		    elasticsearch {
			    hosts => "http://elasticsearch-client-http.elk.svc.cluster.local:9200"
			    index => "smartstore.thecheaper.review-%{+YYYY.MM.dd}"
			    codec => "json"
			    timeout => 120
		    }	
	    } # if end

	# ----------------- 스마트 스토어 티셔츠 topic -----------------

	    else if [topic] =~ "smartstore.180store.review" {
		    elasticsearch {
			    hosts => "http://elasticsearch-client-http.elk.svc.cluster.local:9200"
			    index => "smartstore.180store.review-%{+YYYY.MM.dd}"
			    codec => "json"
			    timeout => 120
		    }	
	    } # if end

	    else if [topic] =~ "smartstore.cloony.review" {
		    elasticsearch {
			    hosts => "http://elasticsearch-client-http.elk.svc.cluster.local:9200"
			    index => "smartstore.cloony.review-%{+YYYY.MM.dd}"
			    codec => "json"
			    timeout => 120
		    }	
	    } # if end

	    else if [topic] =~ "smartstore.theshopsw.review" {
		    elasticsearch {
			    hosts => "http://elasticsearch-client-http.elk.svc.cluster.local:9200"
			    index => "smartstore.theshopsw.review-%{+YYYY.MM.dd}"
			    codec => "json"
			    timeout => 120
		    }	
	    } # if end
    } # output end



      # elasticsearch {
      #     hosts => 
      #     index => "kafka-test-%{+YYYY.MM.dd}"
      #     codec => "json"
      #     timeout => 120    
      # }
    }
