apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: elk
data:
  # logstash conf
  logstash.yml: |
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
    config.reload.automatic: true

# logstash pipeline
  logstash.conf: |
    input {
      kafka {
        bootstrap_servers => "k8s-default-kaf1-115153397e-d1490aa9f4a60a9d.elb.ap-northeast-1.amazonaws.com:9092,k8s-default-kaf2-02002caa46-49a2512fad374462.elb.ap-northeast-1.amazonaws.com:9092,k8s-default-kaf3-eaa91f0a90-f0eeafac11759690.elb.ap-northeast-1.amazonaws.com:9092"
        topics => "test4"
        consumer_threads => 3
      }
    }

    filter {
         mutate {
           gsub => ["message", "[\"/{}]", ""]
         }

         kv {
           field_split => ","
           value_split => ":"
         }
         mutate {
           remove_field => [ "port","@version","host","message" ]
           rename => {" comment" => "comment"}
           rename => {" date" => "date"}
         } # mutate end
      # }
      # else {
      #   drop{}
      # }

        mutate {
          convert => {
            "star" => "integer"
          }
         }
    }

    output {
      stdout {
        codec => rubydebug
      }


      elasticsearch {
          hosts => "http://elasticsearch-client-http.elk.svc.cluster.local:9200"
          index => "kafka-test-%{+YYYY.MM.dd}"
          codec => "json"
          timeout => 120    
      }
    }
