apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: kafka
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      nodeSelector:
        app: kafka
      containers:
      - name: kafka
        image: wurstmeister/kafka
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: BOOTSTRAP_SERVERS
          value: kafka-cluster.kafka.svc.cluster.local:9092
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: 54.180.95.58,13.125.188.93,13.124.87.212
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper.zookeeper.svc.cluster.local:2181"
